### ISSUE TITLE
Build bacula

### ISSUE THREAD

**Issue by domenkozar** [domenkozar/almir#27]
We might download and compile bacula while setting up almir environment. Someday.

**Comment by waa** [comment]
I would suggest no to this.   For example, we use Gentoo for all our servers and Gentoo has a great package management and build system (based on FreeBSD's ports) called portage.

Plus, as a systems administrator, I would never want a 3rd party app/interface program to be responsible for installing the core application for which a server is built for. 

And besides, Gentoo is a built-from-source distro so portage downloads, compiles and installs bacula and all dependencies with one command like so:

emerge bacula

Just my thoughts on this.

**Comment by domenkozar** [comment]
It would be optional. Something like quick installer for lazy people. Of course, advised way is to install system package.

**Comment by domenkozar** [comment]
Changed my mind, it's out of scope of almir to do anything with bacula.
