### ISSUE TITLE
Introduce Fanstatic

### ISSUE THREAD

**Issue by domenkozar** [domenkozar/almir#39]
To better manage CSS/Javascript resources, use Fanstatic.

**Comment by joshuajonah** [comment]
Like this project doesn't have WAY TOO MANY dependencies in the first place. How many packages does it take to run a simple interface? I am considering removing as the virtualenv size is completely out of control.

**Comment by domenkozar** [comment]
Currently it's size is 120MB, I could reduce it to 85MB. Would that help? :)

**Comment by domenkozar** [comment]
Javascript tools have advanced since then, if we happen to care about that, it's going to be part of development tooling
