### ISSUE TITLE
During install always get: No module named psycopg2

### ISSUE THREAD

**Issue by pashinin** [domenkozar/almir#43]
Error itself:
<code>
SQL connection string: postgresql://bacula:12345@localhost/bacula
Connecting to catalog database to verify configuration ...
    Try again: No module named psycopg2
</code>

When I check for this module manually everything is ok
<code>
python
>>>import psycopg2
>>># no error here
</code>

where to dig?

**Comment by domenkozar** [comment]
It should be postgresql+**pg8000**://bacula:12345@localhost/bacula, as instructed in examples :)
