### ISSUE TITLE
installation deps

### ISSUE THREAD

**Issue by glensc** [domenkozar/almir#48]
my [distribution](http://www.pld-linux.org/) has "traceback" python module in python-modules package
so perhaps worth to check it's existence in bootstrap? 

also, maybe worth to fallback to curl, if wget is not present?

```
15:49:47 root[load: 0.41]@pld ~/almir# sh -xec "$(wget -O - https://raw.github.com/iElectric/almir/master/install_production.sh)"
--2013-01-27 15:49:49--  https://raw.github.com/iElectric/almir/master/install_production.sh
Resolving raw.github.com (raw.github.com)... 199.27.76.193
Connecting to raw.github.com (raw.github.com)|199.27.76.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 819 [text/plain]
Saving to: 'STDOUT'

100%[============================================================================================================>] 819         --.-K/s   in 0s      

2013-01-27 15:49:49 (21.9 MB/s) - written to stdout [819/819]

+ set +xe
+ [ -z /usr/bin/python2.7 ]
+ git clone https://github.com/iElectric/almir.git -b latests .
Cloning into '.'...
remote: Counting objects: 1879, done.
remote: Compressing objects: 100% (782/782), done.
remote: Total 1879 (delta 1317), reused 1644 (delta 1082)
Receiving objects: 100% (1879/1879), 534.47 KiB | 248 KiB/s, done.
Resolving deltas: 100% (1317/1317), done.
+ printf [buildout]\nextends = buildout.d/production.cfg
+ >buildout.cfg 
+ /usr/bin/python2.7 bootstrap.py
Traceback (most recent call last):
  File "/usr/share/python2.7/site.py", line 64, in <module>
ImportError: No module named traceback
15:49:53 root[load: 0.46]@pld ~/almir# 
```

**Comment by glensc** [comment]
also i found i need to install:
- gcc
- python-devel-tools for pdb module
- python-devel for Python.h header
- glibc-devel, glibc-headers for devel headers
- sqlite3-devel for sqlite devel headers (sqlite compiling?)

**Comment by domenkozar** [comment]
Thanks for the report! So python-modules is needed in order to have traceback module? If that's the case, I can't do much about that, since traceback is part of python and if distribution decides to include that separately, I can not do much to support that.

Regarding dependencies: thanks, I'll add that to documentation!

**Comment by glensc** [comment]
well, yes, python-modules is linux-distribution specific thing, but worth to mention that you don't need just python-runtime, but also development portion of python. it's quite common to have development parts in subpackages

**Comment by domenkozar** [comment]
I have to disagree, traceback is not a development tool, it's a library to manipulate tracebacks from python, this is used everyday in Python to manipuate traceback formating or when rerasing an exception. 

Apart from that, did you manage to get Almir running?

**Comment by glensc** [comment]
i never said python-modules is development portion. i just said that it's worth to update your doc about required python modules, then if installee runs into trouble can know what packages to install :)

yes. i did, thanks :)

now i'm doing something very heavy: making rpm packages for it's dependencies to be able to install almir with rpm. i have no idea how (and when) what would end up. i hope well :)

**Comment by domenkozar** [comment]
Ah, right, that's a good point. I'll add that on TODO, thanks!

**Comment by domenkozar** [comment]
https://github.com/iElectric/almir/commit/d150f74e23d4ac66858ae7aa58af170b7a8b47fd

I hope you managed to do rpms, I'll shortly put a more detailed description how to package almir (as I just did it for NixOS)
