### ISSUE TITLE
Demo site is unreacheable

### ISSUE THREAD

**Issue by achaussier** [domenkozar/almir#50]
Hello,
For information, the demo site is unreachable.

wget http://almir-demo.domenkozar.com/
--2013-02-20 22:59:44--  http://almir-demo.domenkozar.com/
Résolution de almir-demo.domenkozar.com... 173.0.58.34
Connexion vers almir-demo.domenkozar.com|173.0.58.34|:80...connecté.
requête HTTP transmise, en attente de la réponse...502 Bad Gateway
2013-02-20 22:59:44 ERREUR 502: Bad Gateway

**Comment by domenkozar** [comment]
Thanks for letting me know, I restarted it! http://almir-demo.domenkozar.com/

I will have this open to further investigate what happened and to make sure it won't happen that often (it was about 4 time this month).

**Comment by achaussier** [comment]
Thanks

**Comment by skylineservers** [comment]
Down again :)

**Comment by domenkozar** [comment]
Yeah, it's down for about a year. Never got to pay another server to host it :/
