### ISSUE TITLE
Problem with install_production.sh and buildout

### ISSUE THREAD

**Issue by voileux** [domenkozar/almir#51]
Hello, 

I would like install almir on my CentOS6 to manage a bacula server. 
When i start install_production.sh, I have an error with an import module with buildout. 

When script run bin/buildout, buildout 2.0.1 is used, but in buildout.d/version.cfg you specified version 1.6.3. And when 2.0.1 buildout version is used module is_distribute are not imported and fail compilation. 

So I add -v 1.6.3 on bootstrap.py to use the good version. 

I think you can juste add this option in install_production.sh at line 9. 
$PYTHON_EXEC bootstrap.py -v 1.6.3 

Best Regards. 
## 

Simon

**Comment by lcx** [comment]
thanks, adding -v 1.6.3 worked for me (debian 6)

**Comment by domenkozar** [comment]
Agreed, thanks for reporting this. I'll try to release new version to address this issue.
