### ISSUE TITLE
Problems after installation

### ISSUE THREAD

**Issue by gregsilveira** [domenkozar/almir#69]
Problems after installation.

I've set up an Almir environment following the official documentation: http://almir.readthedocs.org/en/latest/userguide.html#installation but I'm in trouble, please help! :)

My informations:

backup-dir Version: 7.0.5 (28 July 2014)
almir-stderr---supervisor-a29DRB.log http://paste2.org/MnLhFZEg
buildout.cfg: http://paste2.org/V2Nc6f7k

When I'm trying to open Almir at my Firefox browser (latest version) the "502 Bad Gateway - nginx/1.4.6 (Ubuntu)" appears for me.

bconsole was configured to open with the user "bacula", and the Almir was installed to this user.

Thank you!

**Comment by asyd** [comment]
try to change
`pg8000 = 1.09`
to 

`pg8000 = 1.9.2`

in versions.cfg and run

```
bin/buildout
bin/python almir/scripts/configure_deploy.py
bin/buildout -o
```

**Comment by domenkozar** [comment]
This should be fixed now.
