### ISSUE TITLE
7.x Support

### ISSUE THREAD

**Issue by samof76** [domenkozar/almir#70]
Hi.

I know this is not the right forum for this. But does almir support any of the 7.x versions of bacula.

/// Sam

**Comment by asyd** [comment]
Are you sure? I'm using it with bacula 7.0.5

1000 OK: 1 BACULA_DIR Version: 7.0.5 (28 July 2014)

**Comment by domenkozar** [comment]
Sounds like it does. Closing, please reopen with if you get an error/problem.
